name: Build and Release GpuModeDriver

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up WDK
      uses: microsoft/windows-driver-kit@v1
      with:
        version: '10.0.22621.0'  # Adjust to your WDK version

    - name: Build driver
      run: |
        msbuild GpuModeDriver.sln /p:Configuration=Debug /p:Platform=x64

    - name: Create artifacts
      run: |
        Compress-Archive -Path "x64\Debug\GpuModeDriver.sys", "x64\Debug\GpuModeDriver.inf" -DestinationPath "GpuModeDriver.zip"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GpuModeDriver
        path: GpuModeDriver.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: GpuModeDriver

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GpuModeDriver.zip
        asset_name: GpuModeDriver.zip
        asset_content_type: application/zip